name: orders-auth

on:
  pull_request:
    paths:
      - 'orders/**'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and run tests
        run: |
          cd orders
          npm install
          npm run test:ci
