name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and run tests
        run: |
          cd tickets
          npm install
          npm run test:ci
