name: tests-auth

on:
  pull_request:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and run tests
        run: |
          cd auth
          npm install
          npm run test:ci
